apiVersion: v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  source:
    git:
      uri: https://github.com/custom/repository
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: jenkins:latest
        namespace: openshift
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: custom-jenkins:latest